FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /app

COPY . .

WORKDIR "/app/src/Api/Company.Api"
RUN dotnet restore "Company.Api.csproj"
RUN dotnet publish "Company.Api.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

COPY --from=build-env /app/out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Company.Api.dll"]
