FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./

WORKDIR "/src/Api/Company.Api"
RUN dotnet restore "Company.Api.csproj"
RUN dotnet publish "Company.Api.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /App
COPY --from=build-env /App/out .

EXPOSE 80

ENTRYPOINT ["dotnet", "Company.Api.dll"]
