name: "Build apps"
on:
  pull_request:
    branches: [main]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Install dependencies
        run: dotnet restore src/Api/Company.Api.sln
      - name: Build
        run: dotnet build src/Api/Company.Api.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/Api/Company.Api.sln --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish src/Api/Company.Api/Company.Api.csproj -c Release -o publish --runtime linux-x64
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-${{github.event.number}}
          path: src/Api/Company.Api/publish

  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Install dependencies
        run: dotnet restore src/Website/Company.Website.sln
      - name: Build
        run: dotnet build src/Website/Company.Website.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/Website/Company.Website.sln --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish src/Website/Company.Website/Company.Website.csproj -c Release -o publish --runtime linux-x64
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: website-${{github.event.number}}
          path: src/Website/Company.Website/publish
