name: "Deploy - test"
on:
  pull_request:
    branches: [main]

jobs:
  build-api:
    uses: benchiverton/OnlineStore/.github/workflows/workflow-build-test-publish-dotnet.yml@main
    with:
      solution_file: "src/Api/Company.Api.sln"
      project_file: "src/Api/Company.Api/Company.Api.csproj"
      dotnet_version: 6.0.100
      artifact_name: "api"
      self_contained: false

  build-website:
    uses: benchiverton/OnlineStore/.github/workflows/workflow-build-test-publish-dotnet.yml@main
    with:
      solution_file: "src/Website/Company.Website.sln"
      project_file: "src/Website/Company.Website/Company.Website.csproj"
      dotnet_version: 6.0.100
      artifact_name: "website"
      self_contained: true

  deploy-terraform-test:
    needs: [build-api, build-website]
    environment: test
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="container_name=onlinestoretfstate-test" -backend-config="key=terraform.tfstate.${{ github.head_ref }}"
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_location: "East US"
          TF_VAR_environment: ${{ github.head_ref }}
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_location: "East US"
          TF_VAR_environment: ${{ github.head_ref }}
          TF_VAR_dockerhub_username: ${{ secrets.TF_VAR_DOCKERHUB_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.TF_VAR_DOCKERHUB_PASSWORD }}
      - name: Set Application Names
        shell: bash
        run: |
          terraform output -raw app_service_name_api > application-name-test-api.txt
          terraform output -raw app_service_name_website > application-name-test-website.txt
      - name: Upload API application name for deploy job
        uses: actions/upload-artifact@v2
        with:
          name: application-name-test
          path: terraform/application-name-test-api.txt
      - name: Upload website application name for deploy job
        uses: actions/upload-artifact@v2
        with:
          name: application-name-test
          path: terraform/application-name-test-website.txt

  deploy-app-test:
    needs: [deploy-terraform-test]
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download application name
        uses: actions/download-artifact@v2
        with:
          name: application-name-test
      - name: Load application names
        id: vars
        shell: bash
        run: |
          echo ::set-output name=azure_webapp_name_api::$(cat application-name-test-api.txt)
          echo ::set-output name=azure_webapp_name_website::$(cat application-name-test-website.txt)
      - name: Download API package
        uses: actions/download-artifact@v2
        with:
          name: api
          path: ${{ github.workspace }}/api
      - name: Download website package
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ${{ github.workspace }}/website
      - name: Update website config
        run: echo "`jq '.Api.BasePath="https://os-onlinestore-${{ github.head_ref }}-api.azurewebsites.net"' ${{ github.workspace }}/website/wwwroot/appsettings.json`" > ${{ github.workspace }}/website/wwwroot/appsettings.json
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure webapp deploy for API
        uses: azure/webapps-deploy@v2
        id: apideploy
        with:
          app-name: ${{ steps.vars.outputs.azure_webapp_name_api }}
          package: ${{ github.workspace }}/api
      - name: Run Azure webapp deploy for website
        uses: azure/webapps-deploy@v2
        id: websitedeploy
        with:
          app-name: ${{ steps.vars.outputs.azure_webapp_name_website }}
          package: ${{ github.workspace }}/website
      - name: Post test environment information on PR
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Test environment information
            #### 🔗[Visit website](http://os-onlinestore-${{ github.head_ref }}-website.azurewebsites.net/)
            #### 🔗[Visit API](https://os-onlinestore-${{ github.head_ref }}-api.azurewebsites.net/swagger/)

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
