name: Deploy to GihHub Pages

on: [push]

env:
  PROJECT_LOCATION: Web/src/Company.Website/
  PROJECT_FILE: Company.Website.csproj
  BUILD_LOCATION: build/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish with dotnet
      run: dotnet publish ${{ env.PROJECT_LOCATION }}${{ env.PROJECT_FILE }} --configuration Release --output ${{ env.BUILD_LOCATION }}
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{ env.PROJECT_LOCATION }}${{ env.BUILD_LOCATION }}wwwroot
