name: "Instance - deploy prod"
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      monitoring_enabled:
        description: Deploy jaeger instance for monitoring (£20/month)
        type: boolean
        required: true
        default: false

jobs:
  variables:
    steps:
      - name: Set variables needed for workflow
        run: |
          if [[ "${{ inputs.monitoring_enabled}}" == "" ]]
          then
            echo "monitoring_enabled=false"
            echo "monitoring_enabled=false" >> $GITHUB_OUTPUT
          else
            echo "monitoring_enabled=${{ inputs.monitoring_enabled}}"
            echo "monitoring_enabled=${{ inputs.monitoring_enabled}}" >> $GITHUB_OUTPUT
          fi

  build-api:
    uses: benchiverton/OnlineStore/.github/workflows/workflow-build-test-publish-dotnet.yml@main
    with:
      solution_file: "src/Api/Company.Api.sln"
      project_file: "src/Api/Company.Api/Company.Api.csproj"
      dotnet_version: 6.0.100
      artifact_name: "api"
      self_contained: false

  build-website:
    uses: benchiverton/OnlineStore/.github/workflows/workflow-build-test-publish-dotnet.yml@main
    with:
      solution_file: "src/Website/Company.Website.sln"
      project_file: "src/Website/Company.Website/Company.Website.csproj"
      dotnet_version: 6.0.100
      artifact_name: "website"
      self_contained: true

  deploy-terraform-prod:
    needs: [variables, build-api, build-website]
    environment: prod
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Format
        id: fmt
        run: terraform -chdir=instance fmt
      - name: Terraform Init
        id: init
        run: terraform -chdir=instance init -backend-config="container_name=onlinestoretfstate-prod"
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=instance validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=instance plan -no-color
        env:
          TF_VAR_location: "East US"
          TF_VAR_environment: prod
          TF_VAR_acr_username: ${{ secrets.ACR_USERNAME }}
          TF_VAR_acr_password: ${{ secrets.ACR_TOKEN }}
          TF_VAR_monitoring_enabled: ${{ needs.variables.outputs.monitoring_enabled }}
      - name: Terraform Apply
        id: apply
        run: terraform -chdir=instance apply -auto-approve
        env:
          TF_VAR_location: "East US"
          TF_VAR_environment: prod
          TF_VAR_acr_username: ${{ secrets.ACR_USERNAME }}
          TF_VAR_acr_password: ${{ secrets.ACR_TOKEN }}
          TF_VAR_monitoring_enabled: ${{ needs.variables.outputs.monitoring_enabled }}
      - name: Save terraform outputs
        shell: bash
        run: |
          terraform -chdir=instance output -raw web_app_api_name > web_app_api_name.txt
          terraform -chdir=instance output -raw web_app_api_hostname > web_app_api_hostname.txt
          terraform -chdir=instance output -raw web_app_website_name > web_app_website_name.txt
          terraform -chdir=instance output -raw web_app_website_hostname > web_app_website_hostname.txt
          terraform -chdir=instance output -raw container_instance_monitoring_fqdn > container_instance_monitoring_fqdn.txt
      - name: Upload terraform outputs for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: terraform-outputs
          path: terraform/

  deploy-app-prod:
    needs: [deploy-terraform-prod]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download terraform outputs
        uses: actions/download-artifact@v3
        with:
          name: terraform-outputs
      - name: Set terraform outputs as env variables
        id: vars
        shell: bash
        run: |
          echo "web_app_api_name=$(cat web_app_api_name.txt)" >> $GITHUB_ENV
          echo "web_app_api_hostname=$(cat web_app_api_hostname.txt)" >> $GITHUB_ENV
          echo "web_app_website_name=$(cat web_app_website_name.txt)" >> $GITHUB_ENV
          echo "web_app_website_hostname=$(cat web_app_website_hostname.txt)" >> $GITHUB_ENV
          echo "container_instance_monitoring_fqdn=$(cat container_instance_monitoring_fqdn.txt)" >> $GITHUB_ENV
      - name: Download API package
        uses: actions/download-artifact@v3
        with:
          name: api
          path: ${{ github.workspace }}/api
      - name: Download website package
        uses: actions/download-artifact@v3
        with:
          name: website
          path: ${{ github.workspace }}/website
      - name: Update website config
        run: echo "`jq '.Api.BasePath="https://${{ env.web_app_api_hostname }}"' ${{ github.workspace }}/website/wwwroot/appsettings.json`" > ${{ github.workspace }}/website/wwwroot/appsettings.json
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure webapp deploy for API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.web_app_api_name }}
          package: ${{ github.workspace }}/api
      - name: Run Azure webapp deploy for website
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.web_app_website_name }}
          package: ${{ github.workspace }}/website
