name: Permanent - import image to ACR

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
      target_acr:
        required: true

jobs:
  import-image-from-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.target_acr }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Pull image
        run: |
          docker pull docker.io/${{ inputs.image }}
      - name: Re-tag image
        run: |
          docker tag docker.io/${{ inputs.image }} ${{ inputs.target_acr }}/${{ inputs.image }}
      - name: Publish image
        run: |
          docker push ${{ inputs.target_acr }}/${{ inputs.image }}