name: "Deploy Terraform and applications into prod"
on:
  push:
    branches: [main]

jobs:
  deploy-terraform-prod:
    environment: prod
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="container_name=onlinestoretfstate-prod"
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_location: "North Europe"
          TF_VAR_environment: prod
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          TF_VAR_location: "North Europe"
          TF_VAR_environment: prod
      - name: Set Application Name
        shell: bash
        run: |
          terraform output -raw app_service_name > application-name-prod.txt
      - name: Upload application name for deploy job
        uses: actions/upload-artifact@v2
        with:
          name: application-name-prod
          path: terraform/application-name-prod.txt

  app-deploy-prod:
    needs: [deploy-terraform-prod]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download application name
        uses: actions/download-artifact@v2
        with:
          name: application-name-prod
      - name: Load application name
        id: vars
        shell: bash
        run: |
          echo ::set-output name=azure_webapp_name::$(cat application-name-prod.txt)
      - name: Download website package
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ${{ github.workspace }}/website
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure webapp deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.vars.outputs.azure_webapp_name }}
          package: ${{ github.workspace }}/website
