name: "Workflow - build, test and (optionally) publish a dotnet app"
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      project_file:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      self_contained:
        type: boolean
        default: true
      artifact_name:
        type: string
      dockerfile_dir:
        type: string
        default: .
      image_name:
        type: string
      target_acr:
        type: string
        default: onlinestorecontainerregistry.azurecr.io

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Install dependencies
        run: dotnet restore ${{ inputs.solution_file }}
      - name: Build
        run: dotnet build ${{ inputs.solution_file }} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${{ inputs.solution_file }} --configuration Release --no-build --verbosity normal
      - name: Publish binaries
        if: ${{ inputs.artifact_name != null }}        
        run: dotnet publish ${{ inputs.project_file }} --configuration Release --no-build --output publish/${{ inputs.artifact_name }} --self-contained ${{ inputs.self_contained }}
      - name: Publish artifact
        if: ${{ inputs.artifact_name != null }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: publish/${{ inputs.artifact_name }}
      - name: Build and push image
        if: ${{ inputs.image_name != null }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.target_acr }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - run: |
          docker build -f ${{ inputs.dockerfile_dir }} -t ${{ inputs.target_acr }}/${{ inputs.image_name }}:${{ github.run_number }}
          docker push ${{ inputs.target_acr }}/${{ inputs.image_name }}:${{ github.run_number }}
