name: "Workflow - build, test and (optionally) publish a dotnet app"
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      project_file:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      self_contained:
        type: boolean
      artifact_name:
        type: string

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Install dependencies
        run: dotnet restore ${{ inputs.solution_file }}
      - name: Build
        run: dotnet build ${{ inputs.solution_file }} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${{ inputs.solution_file }} --no-build --verbosity normal
      - name: Publish
        if: ${{ inputs.artifact_name != null }}        
        run: dotnet publish ${{ inputs.project_file }} --configuration --no-build --output publish/${{ inputs.artifact_name }} --self-contained ${{ inputs.self_contained }}
      - name: Publish artifact
        if: ${{ inputs.artifact_name != null }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: publish/${{ inputs.artifact_name }}
