name: "Workflow - build, test and (optionally) publish a rust app"
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      dockerfile_name:
        type: string
        default: .
      image_name:
        type: string
      target_acr:
        type: string
        default: onlinestorecontainerregistry.azurecr.io

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: src/Chat
      - name: Build
        run: cargo build --release
        working-directory: ${{ inputs.working_directory }}
      - name: Test
        run: cargo test --release
        working-directory: ${{ inputs.working_directory }}
      - name: Build and push image
        if: ${{ inputs.image_name != null }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.target_acr }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - run: |
          docker image build --file ${{ inputs.dockerfile_name }} --tag ${{ inputs.target_acr }}/${{ inputs.image_name }}:${{ github.sha }} .
          docker push ${{ inputs.target_acr }}/${{ inputs.image_name }}:${{ github.sha }}
        working-directory: ${{ inputs.working_directory }}
